"""add_passenger_info_to_bookings

Revision ID: 4ef8ec06fe2b
Revises: 56d26ac53d6f
Create Date: 2025-12-29 14:58:13.826753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef8ec06fe2b'
down_revision: Union[str, Sequence[str], None] = '56d26ac53d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('first_name', sa.String(length=80), nullable=True))
    op.add_column('bookings', sa.Column('last_name', sa.String(length=80), nullable=True))
    op.add_column('bookings', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('bookings', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'email')
    op.drop_column('bookings', 'birth_date')
    op.drop_column('bookings', 'last_name')
    op.drop_column('bookings', 'first_name')
    # ### end Alembic commands ###
