"""create bookings table

Revision ID: 6fd3bcef8b38
Revises: 
Create Date: 2025-12-27 20:38:30.839626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd3bcef8b38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=120), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=80), nullable=False),
    sa.Column('trip_type', sa.String(length=20), nullable=False),
    sa.Column('cabin', sa.String(length=20), nullable=False),
    sa.Column('depart_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_destination'), 'bookings', ['destination'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_owner_id'), 'bookings', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_owner_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_destination'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
